routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/tentang-kami', function () {
	return view('tentangkami');
});

Route::resources([
	'barang' => 'BarangController',
]);

Route::resources([
	'user' => 'UserController',
]);


Route::group(['middleware' => ['auth']], function () {
	
	Route::resource('/pembelian', 'PembelianController');

	Route::resource('/penjualan', 'PenjualanController');

	Route::get('/about', 'HomeController@about');
});

resources/views/about.blade.php
@extends('layouts-LTE.app')

@section('content')

<section class="content-header">
	<div class="container-fluid">
		<div class="row mb-2">
			<div class="col-sm-6">
				<h1>Tentang Kami</h1>
			</div>
			<div class="col-sm-6">
				<ol class="breadcrumb float-sm-right">
					<li class="breadcrumb-item"><a href="#">Dashboard</a></li>
					<li class="breadcrumb-item active">Tentang Kami</li>
				</ol>
			</div>
		</div>
	</div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">

	<!-- Default box -->
	<div class="card">
		<div class="card-header">
			<h3 class="card-title">Tentang Kami</h3>

		</div>
		<div class="card-body" align="center">
			
			<h1>KELOMPOK 7</h1>
			<h4>Sanber Code - Final Project</h4>
			<ul>
				<li>Muhammad Rully Firmansyah</li>
				<li>Nathania</li>
				<li>Bima</li>
			</ul>

		</div>


	</div>
	<!-- /.card -->

</section>

@endsection

resources/views/barang.blade.php
@extends('layouts-LTE.app')

@section('content')
<div class="content-header">
	<div class="container-fluid">
		<div class="row mb-2">
			<div class="col-sm-6">
				<h1 class="m-0">Master Barang</h1>
			</div><!-- /.col -->
			<div class="col-sm-6">
				<ol class="breadcrumb float-sm-right">
					<li class="breadcrumb-item"><a href="{{ url('/home') }}">Dashboard</a></li>
					<li class="breadcrumb-item active">Master Barang</li>
				</ol>
			</div><!-- /.col -->
		</div><!-- /.row -->
	</div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<section class="content">
	<div class="container-fluid">

		<div class="card">
			<div class="card-header">
				<h3 class="card-title">Data Barang</h3>
			</div>
			<!-- /.card-header -->
			<div class="card-body">
				<div class="col-md-12">
					<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modal-add">
						<i class="fas fa-plus"></i> Tambah Barang
					</button>
				</div>

				<br>

				<table id="example1" class="table table-bordered table-striped">
					<thead>
						<tr>
							<th>#</th>
							<th>Nama Barang</th>
							<th>Harga Barang</th>
							<th>Stok Tersedia (Pcs)</th>
							<th>Aksi</th>
						</tr>
					</thead>
					<tbody>

						@foreach($data as $barang)
						

						<tr>
							<td>{{ $loop->index+1 }}</td>
							<td>{{ $barang->nama_barang }}</td>
							<td>{{ number_format($barang->harga) }}</td>
							<td>{{ $barang->stok }}</td>
							<td>
								
								<button class="btn btn-info" data-toggle="modal" data-target="#modal-edit-{{ $barang->id }}"><i class="fas fa-edit"></i></button>
								<button class="btn btn-danger" data-toggle="modal" data-target="#modal-delete-{{ $barang->id }}"><i class="fas fa-trash"></i></button>
							</td>
						</tr>

						<div class="modal fade" id="modal-edit-{{ $barang->id }}">
							<div class="modal-dialog">
								<div class="modal-content">
									<div class="modal-header">
										<h4 class="modal-title">Ubah Barang</h4>
										<button type="button" class="close" data-dismiss="modal" aria-label="Close">
											<span aria-hidden="true">&times;</span>
										</button>
									</div>
									<form action="{{ url('barang/'.$barang->id) }}" method="post" autocomplete="off">
										@method('put')
										@csrf
										<input type="hidden" name="id" value="{{ $barang->id }}">
										<div class="modal-body">

											<div class="form-group">
												<label for="exampleInputEmail1">Nama Barang</label>
												<input type="text" name="nama" class="form-control" placeholder="Nama Barang" value="{{ $barang->nama_barang }}">
											</div>

											<div class="form-group">
												<label for="exampleInputEmail1">Harga Barang</label>
												<input type="number" name="harga" min="0" class="form-control" placeholder="Harga" value="{{ $barang->harga }}">
											</div>

										</div>
										<div class="modal-footer justify-content-between">
											<button type="button" class="btn btn-default" data-dismiss="modal">Tutup</button>
											<button type="submit" class="btn btn-primary">Simpan</button>
										</div>
									</form>
								</div>
							</div>
						</div>


						<div class="modal fade" id="modal-delete-{{ $barang->id }}">
							<div class="modal-dialog">
								<div class="modal-content bg-warning">
									<div class="modal-header">
										<h4 class="modal-title">Hapus Barang</h4>
										<button type="button" class="close" data-dismiss="modal" aria-label="Close">
											<span aria-hidden="true">&times;</span>
										</button>
									</div>
									<form action="{{ url('barang/'.$barang->id) }}" method="post" autocomplete="off">
										@method('delete')
										@csrf
										<input type="hidden" name="id" value="{{ $barang->id }}">
										<div class="modal-body">
											<p align="center">Apakah Anda Yakin Ingin menghapus barang dengan nama {{ $barang->nama_barang }} ?</p>

										</div>
										<div class="modal-footer justify-content-between">
											<button type="button" class="btn btn-default" data-dismiss="modal">Tutup</button>
											<button type="submit" class="btn btn-danger">Hapus</button>
										</div>
									</form>
								</div>
							</div>
						</div>

						@endforeach


					</tbody>
					<tfoot>
						<tr>
							<th>#</th>
							<th>Nama Barang</th>
							<th>Harga Barang</th>
							<th>Stok Tersedia (Pcs)</th>
							<th>Aksi</th>
						</tr>
					</tfoot>
				</table>
			</div>
			<!-- /.card-body -->
		</div>

	</div>
	<!-- /.row (main row) -->
</div>

</section>
<!-- /.content -->

<div class="modal fade" id="modal-add">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title">Tambah Barang</h4>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<form action="{{ route('barang.store') }}" method="post" autocomplete="off">
				@csrf
				<div class="modal-body">

					<div class="form-group">
						<label for="exampleInputEmail1">Nama Barang</label>
						<input type="text" name="nama" class="form-control" placeholder="Nama Barang">
					</div>

					<div class="form-group">
						<label for="exampleInputEmail1">Harga Barang</label>
						<input type="number" name="harga" min="0" class="form-control" placeholder="Harga">
					</div>

				</div>
				<div class="modal-footer justify-content-between">
					<button type="button" class="btn btn-default" data-dismiss="modal">Tutup</button>
					<button type="submit" class="btn btn-primary">Simpan</button>
				</div>
			</form>
		</div>
	</div>
</div>





@endsection

resources/views/dashboard.blade.php
@extends('layouts-LTE.app')

@section('content')
			<div class="content-header">
				<div class="container-fluid">
					<div class="row mb-2">
						<div class="col-sm-6">
							<h1 class="m-0">Dashboard</h1>
						</div><!-- /.col -->
						<div class="col-sm-6">
							<ol class="breadcrumb float-sm-right">
								<li class="breadcrumb-item"><a href="#">Home</a></li>
								<li class="breadcrumb-item active">Dashboard</li>
							</ol>
						</div><!-- /.col -->
					</div><!-- /.row -->
				</div><!-- /.container-fluid -->
			</div>
			<!-- /.content-header -->

			<!-- Main content -->
			<section class="content">
				<div class="container-fluid" align="center">

					<img src="images/logo.svg" width="60%">

					<h1 align="center">Kelompok 7</h1>
					<h3 align="center">Final Project</h3>

					<div class="row">
						<div class="col-lg-4 col-6">
							<!-- small box -->
							<div class="small-box bg-info">
								<div class="inner">
									<h3>5</h3>

									<p>Data Barang</p>
								</div>
								<div class="icon">
									<i class="ion ion-bag"></i>
								</div>
								<a href="#" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
							</div>
						</div>
						<!-- ./col -->
						<div class="col-lg-4 col-6">
							<!-- small box -->
							<div class="small-box bg-success">
								<div class="inner">
									<h3>N/A</h3>

									<p>Penjualan</p>
								</div>
								<div class="icon">
									<i class="ion ion-stats-bars"></i>
								</div>
								<a href="/penjualan" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
							</div>
						</div>
						<!-- ./col -->
						<div class="col-lg-4 col-6">
							<!-- small box -->
							<div class="small-box bg-warning">
								<div class="inner">
									<h3>N/A</h3>

									<p>Pembelian</p>
								</div>
								<div class="icon">
									<i class="ion ion-person-add"></i>
								</div>
								<a href="/pembelian" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
							</div>
						</div>
						<!-- ./col -->
					</div>
					
				</div>
				<!-- /.row (main row) -->
			</div>
			
		</section>
		<!-- /.content -->



@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/penjualan.blade.php
@extends('layouts-LTE.app')

@section('content')
<div class="content-header">
	<div class="container-fluid">
		<div class="row mb-2">
			<div class="col-sm-6">
				<h1 class="m-0">Penjualan Barang</h1>
			</div><!-- /.col -->
			<div class="col-sm-6">
				<ol class="breadcrumb float-sm-right">
					<li class="breadcrumb-item"><a href="{{ url('/home') }}">Dashboard</a></li>
					<li class="breadcrumb-item active">Penjualan Barang</li>
				</ol>
			</div><!-- /.col -->
		</div><!-- /.row -->
	</div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<section class="content">
	<div class="container-fluid">

		<div class="card">
			<div class="card-header">
				<h3 class="card-title">Penjualan Barang</h3>
			</div>
			<!-- /.card-header -->
			<div class="card-body">
				
			</div>
			<!-- /.card-body -->
		</div>

	</div>
	<!-- /.row (main row) -->
</div>

</section>
<!-- /.content -->



@endsection

resources/views/tentangkami.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Berdikari | Tentang Kami</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@200;600&display=swap" rel="stylesheet">

        <!-- Styles -->
        <style>
            html, body {
                background-color: #000;
                color: #fff;
                font-family: 'Nunito', sans-serif;
                font-weight: 200;
                height: 100vh;
                margin: 0;
            }

            .full-height {
                height: 100vh;
            }

            .flex-center {
                align-items: center;
                display: flex;
                justify-content: center;
            }

            .position-ref {
                position: relative;
            }

            .top-right {
                position: absolute;
                right: 10px;
                top: 18px;
            }

            .content {
                text-align: center;
            }

            .title {
                font-size: 84px;
            }

            .links > a {
                color: #636b6f;
                padding: 0 25px;
                font-size: 13px;
                font-weight: 600;
                letter-spacing: .1rem;
                text-decoration: none;
                text-transform: uppercase;
            }

            .m-b-md {
                margin-bottom: 30px;
            }
        </style>
    </head>
    <body>
        <div class="flex-center position-ref full-height">
            @if (Route::has('login'))
                <div class="top-right links">
                    @auth
                        <a href="{{ url('/') }}">Home</a>
                    @else
                        <a href="{{ url('/') }}">Home</a>
                        <a href="{{ route('login') }}">Login</a>

                        @if (Route::has('register'))
                            <a href="{{ route('register') }}">Register</a>
                        @endif
                    @endauth
                </div>
            @endif

            <div class="content">
                <div class="title m-b-md">
                    Berdikari Sanber
                </div>

                <div class="links">
                    <a href="#">Rully</a>
                    <a href="#">Nathania</a>
                    <a href="#">Bima</a>
                </div>
            </div>
        </div>
    </body>
</html>

resources/views/user.blade.php
@extends('layouts-LTE.app')

@section('content')
<div class="content-header">
	<div class="container-fluid">
		<div class="row mb-2">
			<div class="col-sm-6">
				<h1 class="m-0">Master User</h1>
			</div><!-- /.col -->
			<div class="col-sm-6">
				<ol class="breadcrumb float-sm-right">
					<li class="breadcrumb-item"><a href="{{ url('/home') }}">Dashboard</a></li>
					<li class="breadcrumb-item active">Master User</li>
				</ol>
			</div><!-- /.col -->
		</div><!-- /.row -->
	</div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<section class="content">
	<div class="container-fluid">

		<div class="card">
			<div class="card-header">
				<h3 class="card-title">Data User</h3>
			</div>
			<!-- /.card-header -->
			<div class="card-body">
				<div class="col-md-12">
					<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modal-add">
						<i class="fas fa-plus"></i> Tambah User
					</button>
				</div>

				<br>

				<table id="example1" class="table table-bordered table-striped">
					<thead>
						<tr>
							<th>#</th>
							<th>Nama User</th>
							<th>Email</th>
							<th>Aksi</th>
						</tr>
					</thead>
					<tbody>

						@foreach($data as $user)
						

						<tr>
							<td>{{ $loop->index+1 }}</td>
							<td>{{ $user->name }}</td>
							<td>{{ $user->email }}</td>
							<td>
								
								<button class="btn btn-info" data-toggle="modal" data-target="#modal-edit-{{ $user->id }}"><i class="fas fa-edit"></i></button>
								<button class="btn btn-danger" data-toggle="modal" data-target="#modal-delete-{{ $user->id }}"><i class="fas fa-trash"></i></button>
							</td>
						</tr>

						<div class="modal fade" id="modal-edit-{{ $user->id }}">
							<div class="modal-dialog">
								<div class="modal-content">
									<div class="modal-header">
										<h4 class="modal-title">Ubah User</h4>
										<button type="button" class="close" data-dismiss="modal" aria-label="Close">
											<span aria-hidden="true">&times;</span>
										</button>
									</div>
									<form action="{{ url('user/'.$user->id) }}" method="post" autocomplete="off">
										@method('put')
										@csrf
										<input type="hidden" name="id" value="{{ $user->id }}">
										<div class="modal-body">

											<div class="form-group">
												<label for="exampleInputEmail1">Nama User</label>
												<input type="text" name="name" class="form-control" placeholder="Nama User" value="{{ $user->name }}">
											</div>

											<div class="form-group">
												<label for="exampleInputEmail1">Email</label>
												<input type="email" name="nama" class="form-control" placeholder="Email User" value="{{ $user->email }}">
											</div>

										</div>
										<div class="modal-footer justify-content-between">
											<button type="button" class="btn btn-default" data-dismiss="modal">Tutup</button>
											<button type="submit" class="btn btn-primary">Simpan</button>
										</div>
									</form>
								</div>
							</div>
						</div>


						<div class="modal fade" id="modal-delete-{{ $user->id }}">
							<div class="modal-dialog">
								<div class="modal-content bg-warning">
									<div class="modal-header">
										<h4 class="modal-title">Hapus User</h4>
										<button type="button" class="close" data-dismiss="modal" aria-label="Close">
											<span aria-hidden="true">&times;</span>
										</button>
									</div>
									<form action="{{ url('user/'.$user->id) }}" method="post" autocomplete="off">
										@method('delete')
										@csrf
										<input type="hidden" name="id" value="{{ $user->id }}">
										<div class="modal-body">
											<p align="center">Apakah Anda Yakin Ingin menghapus User dengan nama {{ $user->name }} ?</p>

										</div>
										<div class="modal-footer justify-content-between">
											<button type="button" class="btn btn-default" data-dismiss="modal">Tutup</button>
											<button type="submit" class="btn btn-danger">Hapus</button>
										</div>
									</form>
								</div>
							</div>
						</div>

						@endforeach


					</tbody>
					<tfoot>
						<tr>
							<th>#</th>
							<th>Nama User</th>
							<th>Email User</th>
							<th>Aksi</th>
						</tr>
					</tfoot>
				</table>
			</div>
			<!-- /.card-body -->
		</div>

	</div>
	<!-- /.row (main row) -->
</div>

</section>
<!-- /.content -->

<div class="modal fade" id="modal-add">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title">Tambah User</h4>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<form action="{{ route('user.store') }}" method="post" autocomplete="off">
				@csrf
				<div class="modal-body">

					<div class="form-group">
						<label for="exampleInputEmail1">Nama User</label>
						<input type="text" name="name" class="form-control" placeholder="Nama User" required>
					</div>

					<div class="form-group">
						<label for="exampleInputEmail1">Email User</label>
						<input type="email" name="email" class="form-control" placeholder="Email" required>
					</div>

					<div class="form-group">
						<label for="exampleInputEmail1">Password</label>
						<input type="password" name="password" min="8" class="form-control" placeholder="Password" required>
					</div>

				</div>
				<div class="modal-footer justify-content-between">
					<button type="button" class="btn btn-default" data-dismiss="modal">Tutup</button>
					<button type="submit" class="btn btn-primary">Simpan</button>
				</div>
			</form>
		</div>
	</div>
</div>





@endsection